### ISSUE TITLE
CodeAnalyzer cannot be run successfully with the default VM used in newer Eclipse installs

### ISSUE THREAD

**Issue by scottkurz** [IBM/codenet-minerva-code-analyzer#63]
Eclipse 2024-06 comes configured with a Java 22 version of Hotspot OpenJDK configured by default.   Setting the JAVA_HOME accordingly and running with this 'java' executable on Windows, I get the error below.

If this is an attempt to detect JDK vs JRE then I think it is incomplete.  This distribution certainly has a JDK, it's able to do javac.

It does have a jre/bin/jmod.exe but not 'jmods'.

```
$ 
java  -jar "....codeanalyzer-20241014T185711.jar"  -i C:\git\apps\sample-app-mod -o "....\modresorts" -a 2 --no-build                                                                                 

 java.lang.RuntimeException: java.nio.file.NoSuchFileException:....\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_22.0.2.v20240802-1626\jre\jmods
        at com.ibm.northstar.CodeAnalyzer.run(CodeAnalyzer.java:96)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1767)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2139)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2106)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1973)
        at picocli.CommandLine.execute(CommandLine.java:1902)
        at com.ibm.northstar.CodeAnalyzer.main(CodeAnalyzer.java:85)
Caused by: java.nio.file.NoSuchFileException: ....\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_22.0.2.v20240802-1626\jre\jmods
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:197)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1858)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
        at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
        at java.base/java.nio.file.Files.walk(Files.java:3903)
        at java.base/java.nio.file.Files.walk(Files.java:3958)
        at com.ibm.northstar.utils.ScopeUtils.createScope(ScopeUtils.java:76)
        at com.ibm.northstar.SystemDependencyGraph.construct(SystemDependencyGraph.java:208)
        at com.ibm.northstar.CodeAnalyzer.analyze(CodeAnalyzer.java:169)
        at com.ibm.northstar.CodeAnalyzer.run(CodeAnalyzer.java:94)
```

**Comment by scottkurz** [comment]
Can we just ignore the missing jmods dir?   Please note I wasn't able to actually build and test my PR just trying to move things along.  Thanks

**Comment by rahlk** [comment]
We can add a flag `--jmod-dir` to point to the jmods directory.

**Comment by scottkurz** [comment]
@rahlk would it make any sense to ask if CA could access the needed information via the **jrt-fs.jar** approach rather than jmods?

I'm not sure precisely what I'm asking or even if it truly makes sense.   I was just wondering:  "how does Eclipse compile against standard java.* package/module classes when the JustJ JRE is used in place of a JDK?"

The screenshot here seems to show that jrt-fs.jar plays a role.   Is this helpful or interesting in the idea of avoiding the need for jmods (and a JDK) and using the JustJ JRE?

![image](https://github.com/user-attachments/assets/c7249292-ec84-40aa-9f20-2f8ffc009538)

**Comment by rahlk** [comment]
Hey scott, unfortunately this will not work either. jmods contains dozens of files:

For instance, here are the contents of the `jmods` folder for Java 22. 

```
> ll ~/.sdkman/candidates/java/22.0.1-open/jmods

total 156944
-rw-r--r--  1 rkrsn  staff    20M Mar 12  2024 java.base.jmod
-rw-r--r--  1 rkrsn  staff   129K Mar 12  2024 java.compiler.jmod
-rw-r--r--  1 rkrsn  staff    58K Mar 12  2024 java.datatransfer.jmod
-rw-r--r--  1 rkrsn  staff    13M Mar 12  2024 java.desktop.jmod
-rw-r--r--  1 rkrsn  staff    50K Mar 12  2024 java.instrument.jmod
-rw-r--r--  1 rkrsn  staff   121K Mar 12  2024 java.logging.jmod
-rw-r--r--  1 rkrsn  staff   883K Mar 12  2024 java.management.jmod
-rw-r--r--  1 rkrsn  staff    96K Mar 12  2024 java.management.rmi.jmod
-rw-r--r--  1 rkrsn  staff   474K Mar 12  2024 java.naming.jmod
-rw-r--r--  1 rkrsn  staff   764K Mar 12  2024 java.net.http.jmod
-rw-r--r--  1 rkrsn  staff    88K Mar 12  2024 java.prefs.jmod
-rw-r--r--  1 rkrsn  staff   271K Mar 12  2024 java.rmi.jmod
-rw-r--r--  1 rkrsn  staff    49K Mar 12  2024 java.scripting.jmod
-rw-r--r--  1 rkrsn  staff   9.6K Mar 12  2024 java.se.jmod
-rw-r--r--  1 rkrsn  staff   600K Mar 12  2024 java.security.jgss.jmod
-rw-r--r--  1 rkrsn  staff    87K Mar 12  2024 java.security.sasl.jmod
-rw-r--r--  1 rkrsn  staff    66K Mar 12  2024 java.smartcardio.jmod
-rw-r--r--  1 rkrsn  staff    82K Mar 12  2024 java.sql.jmod
-rw-r--r--  1 rkrsn  staff   196K Mar 12  2024 java.sql.rowset.jmod
-rw-r--r--  1 rkrsn  staff    11K Mar 12  2024 java.transaction.xa.jmod
-rw-r--r--  1 rkrsn  staff   679K Mar 12  2024 java.xml.crypto.jmod
-rw-r--r--  1 rkrsn  staff   4.5M Mar 12  2024 java.xml.jmod
-rw-r--r--  1 rkrsn  staff    56K Mar 12  2024 jdk.accessibility.jmod
-rw-r--r--  1 rkrsn  staff    41K Mar 12  2024 jdk.attach.jmod
-rw-r--r--  1 rkrsn  staff   1.6M Mar 12  2024 jdk.charsets.jmod
-rw-r--r--  1 rkrsn  staff   9.9M Mar 12  2024 jdk.compiler.jmod
-rw-r--r--  1 rkrsn  staff   408K Mar 12  2024 jdk.crypto.cryptoki.jmod
-rw-r--r--  1 rkrsn  staff   9.5K Mar 12  2024 jdk.crypto.ec.jmod
-rw-r--r--  1 rkrsn  staff   160K Mar 12  2024 jdk.dynalink.jmod
-rw-r--r--  1 rkrsn  staff    15K Mar 12  2024 jdk.editpad.jmod
-rw-r--r--  1 rkrsn  staff   9.4K Mar 12  2024 jdk.graal.compiler.jmod
-rw-r--r--  1 rkrsn  staff   9.4K Mar 12  2024 jdk.graal.compiler.management.jmod
-rw-r--r--  1 rkrsn  staff   2.2M Mar 12  2024 jdk.hotspot.agent.jmod
-rw-r--r--  1 rkrsn  staff   162K Mar 12  2024 jdk.httpserver.jmod
-rw-r--r--  1 rkrsn  staff   799K Mar 12  2024 jdk.incubator.vector.jmod
-rw-r--r--  1 rkrsn  staff    15K Mar 12  2024 jdk.internal.ed.jmod
-rw-r--r--  1 rkrsn  staff    90K Mar 12  2024 jdk.internal.jvmstat.jmod
-rw-r--r--  1 rkrsn  staff   455K Mar 12  2024 jdk.internal.le.jmod
-rw-r--r--  1 rkrsn  staff    93K Mar 12  2024 jdk.internal.opt.jmod
-rw-r--r--  1 rkrsn  staff   499K Mar 12  2024 jdk.internal.vm.ci.jmod
-rw-r--r--  1 rkrsn  staff   216K Mar 12  2024 jdk.jartool.jmod
-rw-r--r--  1 rkrsn  staff   1.5M Mar 12  2024 jdk.javadoc.jmod
-rw-r--r--  1 rkrsn  staff   140K Mar 12  2024 jdk.jcmd.jmod
-rw-r--r--  1 rkrsn  staff   476K Mar 12  2024 jdk.jconsole.jmod
-rw-r--r--  1 rkrsn  staff   736K Mar 12  2024 jdk.jdeps.jmod
-rw-r--r--  1 rkrsn  staff   857K Mar 12  2024 jdk.jdi.jmod
-rw-r--r--  1 rkrsn  staff   135K Mar 12  2024 jdk.jdwp.agent.jmod
-rw-r--r--  1 rkrsn  staff   867K Mar 12  2024 jdk.jfr.jmod
-rw-r--r--  1 rkrsn  staff   440K Mar 12  2024 jdk.jlink.jmod
-rw-r--r--  1 rkrsn  staff   723K Mar 12  2024 jdk.jpackage.jmod
-rw-r--r--  1 rkrsn  staff   751K Mar 12  2024 jdk.jshell.jmod
-rw-r--r--  1 rkrsn  staff    11K Mar 12  2024 jdk.jsobject.jmod
-rw-r--r--  1 rkrsn  staff    38K Mar 12  2024 jdk.jstatd.jmod
-rw-r--r--  1 rkrsn  staff    11M Mar 12  2024 jdk.localedata.jmod
-rw-r--r--  1 rkrsn  staff    84K Mar 12  2024 jdk.management.agent.jmod
-rw-r--r--  1 rkrsn  staff    61K Mar 12  2024 jdk.management.jfr.jmod
-rw-r--r--  1 rkrsn  staff    81K Mar 12  2024 jdk.management.jmod
-rw-r--r--  1 rkrsn  staff    70K Mar 12  2024 jdk.naming.dns.jmod
-rw-r--r--  1 rkrsn  staff    30K Mar 12  2024 jdk.naming.rmi.jmod
-rw-r--r--  1 rkrsn  staff    35K Mar 12  2024 jdk.net.jmod
-rw-r--r--  1 rkrsn  staff    10K Mar 12  2024 jdk.nio.mapmode.jmod
-rw-r--r--  1 rkrsn  staff    29K Mar 12  2024 jdk.random.jmod
-rw-r--r--  1 rkrsn  staff    31K Mar 12  2024 jdk.sctp.jmod
-rw-r--r--  1 rkrsn  staff    78K Mar 12  2024 jdk.security.auth.jmod
-rw-r--r--  1 rkrsn  staff    32K Mar 12  2024 jdk.security.jgss.jmod
-rw-r--r--  1 rkrsn  staff    21K Mar 12  2024 jdk.unsupported.desktop.jmod
-rw-r--r--  1 rkrsn  staff    25K Mar 12  2024 jdk.unsupported.jmod
-rw-r--r--  1 rkrsn  staff    49K Mar 12  2024 jdk.xml.dom.jmod
-rw-r--r--  1 rkrsn  staff   111K Mar 12  2024 jdk.zipfs.jmod
```
