### ISSUE TITLE
Wrong path to mvn executable on Windows - should be mvn.cmd not mvn.bat

### ISSUE THREAD

**Issue by scottkurz** [IBM/codenet-minerva-code-analyzer#73]
Using v1.0.4:

this should be mvn.cmd not mvn.bat

```
java.io.IOException: Cannot run program "mvn.bat": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at com.ibm.cldk.utils.BuildProject.buildWithTool(BuildProject.java:67)
	at com.ibm.cldk.utils.BuildProject.downloadLibraryDependencies(BuildProject.java:192)
	at com.ibm.cldk.CodeAnalyzer.analyze(CodeAnalyzer.java:122)
	at com.ibm.cldk.CodeAnalyzer.run(CodeAnalyzer.java:103)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1767)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2139)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2106)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1973)
	at picocli.CommandLine.execute(CommandLine.java:1902)
	at com.ibm.cldk.CodeAnalyzer.main(CodeAnalyzer.java:94)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 12 more
```

**Comment by scottkurz** [comment]
Looks like this has been fixed in main already.
