### ISSUE TITLE
It seems that code analyzer assumes that gradle projects always has a wrapper(gradlew)

### ISSUE THREAD

**Issue by fabio-franco** [IBM/codenet-minerva-code-analyzer#79]
I'm testing the code analyzer at https://github.com/hammingweight/gradle-java-ear but shows

```
java.io.IOException: Cannot run program "/Users/fabiofranco/Development/git/wca4j/svt/gradle-java-ear/gradlew": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.ibm.cldk.utils.BuildProject.buildWithTool(BuildProject.java:68)
	at com.ibm.cldk.utils.BuildProject.downloadLibraryDependencies(BuildProject.java:199)
	at com.ibm.cldk.CodeAnalyzer.analyze(CodeAnalyzer.java:122)
	at com.ibm.cldk.CodeAnalyzer.run(CodeAnalyzer.java:103)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1767)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2139)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2106)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1973)
	at picocli.CommandLine.execute(CommandLine.java:1902)
	at com.ibm.cldk.CodeAnalyzer.main(CodeAnalyzer.java:94)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 12 more
```
So, it seems that it assumes that the project has gradle wrapper (gradlew) to use. See full log:

```
java -Xms512m -Xmx4096m -jar codeanalyzer-1.0.6.jar -i /Users/fabiofranco/Development/git/wca4j/svt/gradle-java-ear -o /Users/fabiofranco/.wca/codeAnalyzer/gradle-java-ear --project-root-path /Users/fabiofranco/Development/git/wca4j/svt/gradle-java-ear --no-build -a 2 -v 
2024-12-02T15:54:41.241298	[INFO]	Found build.gradle[.kts] in the project directory. Using Gradle to download dependencies.
[/Users/fabiofranco/Development/git/wca4j/svt/gradle-java-ear/gradlew, --init-script, /var/folders/93/w44chfb90jjbk3f0vhk85frc0000gn/T/gradle-init-14231273622998023167.gradle, downloadDependencies, -PoutputDir=/Users/fabiofranco/Development/git/wca4j/svt/gradle-java-ear/_library_dependencies]
2024-12-02T15:54:41.269185	[INFO]	Building the project using /Users/fabiofranco/Development/git/wca4j/svt/gradle-java-ear/gradlew.
java.io.IOException: Cannot run program "/Users/fabiofranco/Development/git/wca4j/svt/gradle-java-ear/gradlew": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.ibm.cldk.utils.BuildProject.buildWithTool(BuildProject.java:68)
	at com.ibm.cldk.utils.BuildProject.downloadLibraryDependencies(BuildProject.java:199)
	at com.ibm.cldk.CodeAnalyzer.analyze(CodeAnalyzer.java:122)
	at com.ibm.cldk.CodeAnalyzer.run(CodeAnalyzer.java:103)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1767)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2139)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2106)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1973)
	at picocli.CommandLine.execute(CommandLine.java:1902)
	at com.ibm.cldk.CodeAnalyzer.main(CodeAnalyzer.java:94)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 12 more
2024-12-02T15:54:41.279875	[WARN]	Failed to download library dependencies of project
2024-12-02T15:54:41.649171	[WARN]	Could not resolve type: EntityManager: Unsolved symbol : EntityManager
2024-12-02T15:54:41.710551	[DEBUG]	Could not resolve expression: em: Unsolved symbol : EntityManager
2024-12-02T15:54:41.711669	[DEBUG]	Could not resolve expression: em.persist(message): Unsolved symbol : EntityManager
2024-12-02T15:54:41.713038	[DEBUG]	Could not resolve method call: em.persist(message): Unsolved symbol in em.persist(message) : em
2024-12-02T15:54:41.713953	[DEBUG]	Could not resolve access specifier for method call: em.persist(message): Unsolved symbol in em.persist(message) : em
2024-12-02T15:54:41.724703	[DEBUG]	Could not resolve expression: em.createNamedQuery("findMessages"): Unsolved symbol : EntityManager
2024-12-02T15:54:41.725737	[DEBUG]	Could not resolve expression: em.createNamedQuery("findMessages").getResultList(): Unsolved symbol : EntityManager
2024-12-02T15:54:41.726882	[DEBUG]	Could not resolve method call: em.createNamedQuery("findMessages").getResultList(): Unsolved symbol in em.createNamedQuery("findMessages").getResultList() : em.createNamedQuery("findMessages")
2024-12-02T15:54:41.728019	[DEBUG]	Could not resolve access specifier for method call: em.createNamedQuery("findMessages").getResultList(): Unsolved symbol in em.createNamedQuery("findMessages").getResultList() : em.createNamedQuery("findMessages")
2024-12-02T15:54:41.729243	[DEBUG]	Could not resolve method call: em.createNamedQuery("findMessages"): Unsolved symbol in em.createNamedQuery("findMessages") : em
2024-12-02T15:54:41.730072	[DEBUG]	Could not resolve access specifier for method call: em.createNamedQuery("findMessages"): Unsolved symbol in em.createNamedQuery("findMessages") : em
2024-12-02T15:54:41.746726	[DEBUG]	Could not resolve expression: em.createNamedQuery("deleteMessages"): Unsolved symbol : EntityManager
2024-12-02T15:54:41.747750	[DEBUG]	Could not resolve expression: em.createNamedQuery("deleteMessages").executeUpdate(): Unsolved symbol : EntityManager
2024-12-02T15:54:41.748812	[DEBUG]	Could not resolve method call: em.createNamedQuery("deleteMessages").executeUpdate(): Unsolved symbol in em.createNamedQuery("deleteMessages").executeUpdate() : em.createNamedQuery("deleteMessages")
2024-12-02T15:54:41.750092	[DEBUG]	Could not resolve access specifier for method call: em.createNamedQuery("deleteMessages").executeUpdate(): Unsolved symbol in em.createNamedQuery("deleteMessages").executeUpdate() : em.createNamedQuery("deleteMessages")
2024-12-02T15:54:41.750980	[DEBUG]	Could not resolve method call: em.createNamedQuery("deleteMessages"): Unsolved symbol in em.createNamedQuery("deleteMessages") : em
2024-12-02T15:54:41.751704	[DEBUG]	Could not resolve access specifier for method call: em.createNamedQuery("deleteMessages"): Unsolved symbol in em.createNamedQuery("deleteMessages") : em
2024-12-02T15:54:41.767230	[WARN]	Could not resolve type: EntityManagerFactory: Unsolved symbol : EntityManagerFactory
2024-12-02T15:54:41.771704	[DEBUG]	Could not resolve expression: ejb.em: Unsolved symbol : em
2024-12-02T15:54:41.774032	[DEBUG]	Could not resolve expression: Persistence: Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.774722	[DEBUG]	Could not resolve expression: Persistence.createEntityManagerFactory("ejb-tests-pu"): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.775191	[DEBUG]	Could not resolve method call: Persistence.createEntityManagerFactory("ejb-tests-pu"): Unsolved symbol in Persistence.createEntityManagerFactory("ejb-tests-pu") : Persistence
2024-12-02T15:54:41.775827	[DEBUG]	Could not resolve access specifier for method call: Persistence.createEntityManagerFactory("ejb-tests-pu"): Unsolved symbol in Persistence.createEntityManagerFactory("ejb-tests-pu") : Persistence
2024-12-02T15:54:41.777579	[DEBUG]	Could not resolve expression: emf: Unsolved symbol : EntityManagerFactory
2024-12-02T15:54:41.778228	[DEBUG]	Could not resolve expression: emf.createEntityManager(): Unsolved symbol : EntityManagerFactory
2024-12-02T15:54:41.778820	[DEBUG]	Could not resolve method call: emf.createEntityManager(): Unsolved symbol in emf.createEntityManager() : emf
2024-12-02T15:54:41.779462	[DEBUG]	Could not resolve access specifier for method call: emf.createEntityManager(): Unsolved symbol in emf.createEntityManager() : emf
2024-12-02T15:54:41.781086	[WARN]	Could not resolve type: EntityTransaction: Unsolved symbol : EntityTransaction
2024-12-02T15:54:41.783361	[DEBUG]	Could not resolve expression: ejb.em.getTransaction(): Unsolved symbol : em
2024-12-02T15:54:41.785110	[DEBUG]	Could not resolve method call: ejb.em.getTransaction(): Unsolved symbol in ejb.em.getTransaction() : ejb.em
2024-12-02T15:54:41.785983	[DEBUG]	Could not resolve access specifier for method call: ejb.em.getTransaction(): Unsolved symbol in ejb.em.getTransaction() : ejb.em
2024-12-02T15:54:41.787813	[DEBUG]	Could not resolve expression: tx: Unsolved symbol : EntityTransaction
2024-12-02T15:54:41.788498	[DEBUG]	Could not resolve expression: tx.begin(): Unsolved symbol : EntityTransaction
2024-12-02T15:54:41.789212	[DEBUG]	Could not resolve method call: tx.begin(): Unsolved symbol in tx.begin() : tx
2024-12-02T15:54:41.789681	[DEBUG]	Could not resolve access specifier for method call: tx.begin(): Unsolved symbol in tx.begin() : tx
2024-12-02T15:54:41.790206	[DEBUG]	Could not resolve expression: ejb.em.createQuery("delete from Message"): Unsolved symbol : em
2024-12-02T15:54:41.790927	[DEBUG]	Could not resolve expression: ejb.em.createQuery("delete from Message").executeUpdate(): Unsolved symbol : em
2024-12-02T15:54:41.791496	[DEBUG]	Could not resolve method call: ejb.em.createQuery("delete from Message").executeUpdate(): Unsolved symbol in ejb.em.createQuery("delete from Message").executeUpdate() : ejb.em.createQuery("delete from Message")
2024-12-02T15:54:41.792044	[DEBUG]	Could not resolve access specifier for method call: ejb.em.createQuery("delete from Message").executeUpdate(): Unsolved symbol in ejb.em.createQuery("delete from Message").executeUpdate() : ejb.em.createQuery("delete from Message")
2024-12-02T15:54:41.792774	[DEBUG]	Could not resolve method call: ejb.em.createQuery("delete from Message"): Unsolved symbol in ejb.em.createQuery("delete from Message") : ejb.em
2024-12-02T15:54:41.793385	[DEBUG]	Could not resolve access specifier for method call: ejb.em.createQuery("delete from Message"): Unsolved symbol in ejb.em.createQuery("delete from Message") : ejb.em
2024-12-02T15:54:41.793869	[DEBUG]	Could not resolve expression: tx.commit(): Unsolved symbol : EntityTransaction
2024-12-02T15:54:41.794266	[DEBUG]	Could not resolve method call: tx.commit(): Unsolved symbol in tx.commit() : tx
2024-12-02T15:54:41.794678	[DEBUG]	Could not resolve access specifier for method call: tx.commit(): Unsolved symbol in tx.commit() : tx
2024-12-02T15:54:41.795278	[DEBUG]	Could not resolve expression: ejb.em.close(): Unsolved symbol : em
2024-12-02T15:54:41.795899	[DEBUG]	Could not resolve method call: ejb.em.close(): Unsolved symbol in ejb.em.close() : ejb.em
2024-12-02T15:54:41.796583	[DEBUG]	Could not resolve access specifier for method call: ejb.em.close(): Unsolved symbol in ejb.em.close() : ejb.em
2024-12-02T15:54:41.797361	[DEBUG]	Could not resolve expression: emf.close(): Unsolved symbol : EntityManagerFactory
2024-12-02T15:54:41.797877	[DEBUG]	Could not resolve method call: emf.close(): Unsolved symbol in emf.close() : emf
2024-12-02T15:54:41.798340	[DEBUG]	Could not resolve access specifier for method call: emf.close(): Unsolved symbol in emf.close() : emf
2024-12-02T15:54:41.802391	[DEBUG]	Could not resolve method call: ejb.em.getTransaction(): Unsolved symbol in ejb.em.getTransaction() : ejb.em
2024-12-02T15:54:41.802921	[DEBUG]	Could not resolve access specifier for method call: ejb.em.getTransaction(): Unsolved symbol in ejb.em.getTransaction() : ejb.em
2024-12-02T15:54:41.803382	[DEBUG]	Could not resolve method call: tx.begin(): Unsolved symbol in tx.begin() : tx
2024-12-02T15:54:41.803828	[DEBUG]	Could not resolve access specifier for method call: tx.begin(): Unsolved symbol in tx.begin() : tx
2024-12-02T15:54:41.807730	[DEBUG]	Could not resolve method call: tx.commit(): Unsolved symbol in tx.commit() : tx
2024-12-02T15:54:41.808057	[DEBUG]	Could not resolve access specifier for method call: tx.commit(): Unsolved symbol in tx.commit() : tx
2024-12-02T15:54:41.808535	[DEBUG]	Could not resolve expression: ejb.em.createQuery("select count(m) from Message m"): Unsolved symbol : em
2024-12-02T15:54:41.809352	[DEBUG]	Could not resolve method call: ejb.em.createQuery("select count(m) from Message m").getSingleResult(): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m").getSingleResult() : ejb.em.createQuery("select count(m) from Message m")
2024-12-02T15:54:41.809852	[DEBUG]	Could not resolve access specifier for method call: ejb.em.createQuery("select count(m) from Message m").getSingleResult(): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m").getSingleResult() : ejb.em.createQuery("select count(m) from Message m")
2024-12-02T15:54:41.810549	[DEBUG]	Could not resolve method call: ejb.em.createQuery("select count(m) from Message m"): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m") : ejb.em
2024-12-02T15:54:41.811192	[DEBUG]	Could not resolve access specifier for method call: ejb.em.createQuery("select count(m) from Message m"): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m") : ejb.em
2024-12-02T15:54:41.811930	[DEBUG]	Could not resolve expression: assertEquals(1, numEntries): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.812424	[DEBUG]	Could not resolve method call: assertEquals(1, numEntries): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.812913	[DEBUG]	Could not resolve access specifier for method call: assertEquals(1, numEntries): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.816914	[DEBUG]	Could not resolve expression: assertTrue(message.contains("some statistically improbable phrase")): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.817240	[DEBUG]	Could not resolve method call: assertTrue(message.contains("some statistically improbable phrase")): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.817491	[DEBUG]	Could not resolve access specifier for method call: assertTrue(message.contains("some statistically improbable phrase")): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.822110	[DEBUG]	Could not resolve expression: assertEquals(0, (long) ejb.em.createQuery("select count(m) from Message m").getSingleResult()): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.822502	[DEBUG]	Could not resolve method call: assertEquals(0, (long) ejb.em.createQuery("select count(m) from Message m").getSingleResult()): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.822805	[DEBUG]	Could not resolve access specifier for method call: assertEquals(0, (long) ejb.em.createQuery("select count(m) from Message m").getSingleResult()): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.823820	[DEBUG]	Could not resolve method call: ejb.em.createQuery("select count(m) from Message m").getSingleResult(): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m").getSingleResult() : ejb.em.createQuery("select count(m) from Message m")
2024-12-02T15:54:41.824384	[DEBUG]	Could not resolve access specifier for method call: ejb.em.createQuery("select count(m) from Message m").getSingleResult(): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m").getSingleResult() : ejb.em.createQuery("select count(m) from Message m")
2024-12-02T15:54:41.825104	[DEBUG]	Could not resolve method call: ejb.em.createQuery("select count(m) from Message m"): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m") : ejb.em
2024-12-02T15:54:41.825687	[DEBUG]	Could not resolve access specifier for method call: ejb.em.createQuery("select count(m) from Message m"): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m") : ejb.em
2024-12-02T15:54:41.826452	[DEBUG]	Could not resolve method call: ejb.em.getTransaction(): Unsolved symbol in ejb.em.getTransaction() : ejb.em
2024-12-02T15:54:41.827185	[DEBUG]	Could not resolve access specifier for method call: ejb.em.getTransaction(): Unsolved symbol in ejb.em.getTransaction() : ejb.em
2024-12-02T15:54:41.827838	[DEBUG]	Could not resolve method call: tx.begin(): Unsolved symbol in tx.begin() : tx
2024-12-02T15:54:41.828311	[DEBUG]	Could not resolve access specifier for method call: tx.begin(): Unsolved symbol in tx.begin() : tx
2024-12-02T15:54:41.830135	[DEBUG]	Could not resolve method call: tx.commit(): Unsolved symbol in tx.commit() : tx
2024-12-02T15:54:41.830553	[DEBUG]	Could not resolve access specifier for method call: tx.commit(): Unsolved symbol in tx.commit() : tx
2024-12-02T15:54:41.831131	[DEBUG]	Could not resolve expression: assertEquals(1, (long) ejb.em.createQuery("select count(m) from Message m").getSingleResult()): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.831584	[DEBUG]	Could not resolve method call: assertEquals(1, (long) ejb.em.createQuery("select count(m) from Message m").getSingleResult()): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.831854	[DEBUG]	Could not resolve access specifier for method call: assertEquals(1, (long) ejb.em.createQuery("select count(m) from Message m").getSingleResult()): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.832576	[DEBUG]	Could not resolve method call: ejb.em.createQuery("select count(m) from Message m").getSingleResult(): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m").getSingleResult() : ejb.em.createQuery("select count(m) from Message m")
2024-12-02T15:54:41.833040	[DEBUG]	Could not resolve access specifier for method call: ejb.em.createQuery("select count(m) from Message m").getSingleResult(): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m").getSingleResult() : ejb.em.createQuery("select count(m) from Message m")
2024-12-02T15:54:41.833782	[DEBUG]	Could not resolve method call: ejb.em.createQuery("select count(m) from Message m"): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m") : ejb.em
2024-12-02T15:54:41.834383	[DEBUG]	Could not resolve access specifier for method call: ejb.em.createQuery("select count(m) from Message m"): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m") : ejb.em
2024-12-02T15:54:41.834878	[DEBUG]	Could not resolve method call: tx.begin(): Unsolved symbol in tx.begin() : tx
2024-12-02T15:54:41.835252	[DEBUG]	Could not resolve access specifier for method call: tx.begin(): Unsolved symbol in tx.begin() : tx
2024-12-02T15:54:41.836291	[DEBUG]	Could not resolve method call: tx.commit(): Unsolved symbol in tx.commit() : tx
2024-12-02T15:54:41.836683	[DEBUG]	Could not resolve access specifier for method call: tx.commit(): Unsolved symbol in tx.commit() : tx
2024-12-02T15:54:41.837025	[DEBUG]	Could not resolve method call: assertEquals(0, (long) ejb.em.createQuery("select count(m) from Message m").getSingleResult()): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.837270	[DEBUG]	Could not resolve access specifier for method call: assertEquals(0, (long) ejb.em.createQuery("select count(m) from Message m").getSingleResult()): Unsolved symbol : org.junit.Assert
2024-12-02T15:54:41.837898	[DEBUG]	Could not resolve method call: ejb.em.createQuery("select count(m) from Message m").getSingleResult(): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m").getSingleResult() : ejb.em.createQuery("select count(m) from Message m")
2024-12-02T15:54:41.838328	[DEBUG]	Could not resolve access specifier for method call: ejb.em.createQuery("select count(m) from Message m").getSingleResult(): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m").getSingleResult() : ejb.em.createQuery("select count(m) from Message m")
2024-12-02T15:54:41.838957	[DEBUG]	Could not resolve method call: ejb.em.createQuery("select count(m) from Message m"): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m") : ejb.em
2024-12-02T15:54:41.839492	[DEBUG]	Could not resolve access specifier for method call: ejb.em.createQuery("select count(m) from Message m"): Unsolved symbol in ejb.em.createQuery("select count(m) from Message m") : ejb.em
2024-12-02T15:54:41.857473	[WARN]	Could not resolve type: HttpServlet: Unsolved symbol : HttpServlet
2024-12-02T15:54:41.859267	[WARN]	Could not resolve type: ServletException: Unsolved symbol : ServletException
2024-12-02T15:54:41.860722	[WARN]	Could not resolve type: HttpServletRequest: Unsolved symbol : HttpServletRequest
2024-12-02T15:54:41.861913	[WARN]	Could not resolve type: HttpServletResponse: Unsolved symbol : HttpServletResponse
2024-12-02T15:54:41.863901	[DEBUG]	Could not resolve expression: request: Unsolved symbol : HttpServletRequest
2024-12-02T15:54:41.864946	[DEBUG]	Could not resolve expression: request.getParameter(PUT_MESSAGE): Unsolved symbol : HttpServletRequest
2024-12-02T15:54:41.865620	[DEBUG]	Could not resolve method call: request.getParameter(PUT_MESSAGE): Unsolved symbol in request.getParameter(PUT_MESSAGE) : request
2024-12-02T15:54:41.866037	[DEBUG]	Could not resolve access specifier for method call: request.getParameter(PUT_MESSAGE): Unsolved symbol in request.getParameter(PUT_MESSAGE) : request
2024-12-02T15:54:41.873343	[DEBUG]	Could not resolve expression: response: Unsolved symbol : HttpServletResponse
2024-12-02T15:54:41.873919	[DEBUG]	Could not resolve expression: response.sendRedirect("./DisplayServlet"): Unsolved symbol : HttpServletResponse
2024-12-02T15:54:41.874309	[DEBUG]	Could not resolve method call: response.sendRedirect("./DisplayServlet"): Unsolved symbol in response.sendRedirect("./DisplayServlet") : response
2024-12-02T15:54:41.874659	[DEBUG]	Could not resolve access specifier for method call: response.sendRedirect("./DisplayServlet"): Unsolved symbol in response.sendRedirect("./DisplayServlet") : response
2024-12-02T15:54:41.875183	[DEBUG]	Could not resolve constructor call: new ServletException(nme): Unsolved symbol : ServletException
2024-12-02T15:54:41.877777	[DEBUG]	Could not resolve expression: response.setContentType("text/html;charset=UTF-8"): Unsolved symbol : HttpServletResponse
2024-12-02T15:54:41.878305	[DEBUG]	Could not resolve method call: response.setContentType("text/html;charset=UTF-8"): Unsolved symbol in response.setContentType("text/html;charset=UTF-8") : response
2024-12-02T15:54:41.878859	[DEBUG]	Could not resolve access specifier for method call: response.setContentType("text/html;charset=UTF-8"): Unsolved symbol in response.setContentType("text/html;charset=UTF-8") : response
2024-12-02T15:54:41.879469	[DEBUG]	Could not resolve expression: response.getWriter(): Unsolved symbol : HttpServletResponse
2024-12-02T15:54:41.879831	[DEBUG]	Could not resolve method call: response.getWriter(): Unsolved symbol in response.getWriter() : response
2024-12-02T15:54:41.880174	[DEBUG]	Could not resolve access specifier for method call: response.getWriter(): Unsolved symbol in response.getWriter() : response
2024-12-02T15:54:41.930998	[INFO]	Create analysis scope.
2024-12-02T15:54:41.952308	[INFO]	Add exclusions to scope.
2024-12-02T15:54:41.952466	[INFO]	Loading Java SE standard libs.
2024-12-02T15:54:41.972661	[WARN]	No extra libraries to process.
2024-12-02T15:54:41.983673	[INFO]	Finding *.class files in /Users/fabiofranco/Development/git/wca4j/svt/gradle-java-ear
2024-12-02T15:54:41.992952	[DEBUG]	Application class files: 6
2024-12-02T15:54:41.993004	[INFO]	Adding application classes to scope.
2024-12-02T15:54:44.109104	[DONE]	There were a total of 28796 classes of which 4 are application classes.
2024-12-02T15:54:44.127723	[INFO]	Registered 15 entrypoints.
2024-12-02T15:54:44.134966	[INFO]	Building call graph.
2024-12-02T15:54:57.596074	[DONE]	Finished construction of call graph. Took 14.0 seconds.
2024-12-02T15:54:57.962997	[INFO]	Building System Dependency Graph.
2024-12-02T15:54:58.358072	[INFO]	Cleaning up library dependency directory: /Users/fabiofranco/Development/git/wca4j/svt/gradle-java-ear/_library_dependencies
2024-12-02T15:54:58.386676	[DONE]	Analysis output saved at /Users/fabiofranco/.wca/codeAnalyzer/gradle-java-ear
```

Note: since https://github.com/hammingweight/gradle-java-ear is an old project, I was able to build it using Java 8 and Gradle 5 (installed via SDK man).

**Comment by rahlk** [comment]
Fixed in PR #80, and tested using gradle 5.6.4.
