### ISSUE TITLE
Code analyzer fails in maven projects when Gradle is not found

### ISSUE THREAD

**Issue by fabio-franco** [IBM/codenet-minerva-code-analyzer#82]
There is a gradle requirement on code analyzer 1.0.7 even when trying to run maven projects:

```
/Users/fabiofranco/.sdkman/candidates/java/current/bin/java -Xms512m -Xmx4096m -jar codeanalyzer-1.0.7.jar -i /Users/fabiofranco/Development/git/wca4j/svt/erww-lite -o /Users/fabiofranco/.wca/codeAnalyzer/erww-lite --project-root-path /Users/fabiofranco/Development/git/wca4j/svt/erww-lite --no-build -a 2 -v
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:206)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:195)
	at com.ibm.cldk.CodeAnalyzer.analyze(CodeAnalyzer.java:121)
	at com.ibm.cldk.CodeAnalyzer.run(CodeAnalyzer.java:101)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1767)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2139)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2106)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1973)
	at picocli.CommandLine.execute(CommandLine.java:1902)
	at com.ibm.cldk.CodeAnalyzer.main(CodeAnalyzer.java:92)
Caused by: java.lang.IllegalStateException: Could not file a valid gradle command. I did not find gradlew or gradle in the project directory or in the system PATH.
	at com.ibm.cldk.utils.BuildProject.getGradleCmd(BuildProject.java:61)
	at com.ibm.cldk.utils.BuildProject.<clinit>(BuildProject.java:24)
	... 9 more
```

Steps:
1. Make sure you don't have gradle installed in your machine:
```
gradle -v
zsh: command not found: gradle
```
2. Try to run the code analyzer over a maven project, which does not have any gradle file. For example, you can use `https://github.ibm.com/was-svt/erww-lite` or any other maven project.
3. See the error when trying to run the code analyzer, as shown above.

Note: We consider this a critical issue and we need a fix asap!

**Comment by rahlk** [comment]
@fabio-franco I just ran codeanalyzer 1.0.7 as per your instructions, and I can't recreate this issue.

Please see the below log, and the generated analysis.json file.

My build environment:
- Java 11
- Codeanalyzer 1.0.7

Run log: [codeanalyzer-1.0.7-erww-on-java11.txt](https://github.com/user-attachments/files/18113620/codeanalyzer-1.0.7-erww-on-java11.txt)

**Comment by rahlk** [comment]
Update: I have verified this issue does not occur both with java 17 and java 21.

**Comment by rofrano** [comment]
Here is a reproducible test case using `aster-cli` as the test environment:

```bash
$ wget https://github.com/IBM/codenet-minerva-code-analyzer/releases/download/v1.0.7/codeanalyzer-1.0.7.jar

$ docker run --rm -it -h dev -v $(pwd):/app -w /app mcr.microsoft.com/devcontainers/java:1-21-bullseye bash

$ apt-get update && apt-get install -y maven

$ mvn --version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 21.0.2, vendor: Microsoft, runtime: /usr/lib/jvm/msopenjdk-current
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.6.51-0-virt", arch: "amd64", family: "unix"

$ gradle --version
bash: gradle: command not found

$ java -jar codeanalyzer-1.0.7.jar -v -i './resources/datasets/commons-cli' -a 2 -o './output/commons-cli'
```

The output is clearly looking for Gradle:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.ibm.cldk.CodeAnalyzer.analyze(CodeAnalyzer.java:121)
	at com.ibm.cldk.CodeAnalyzer.run(CodeAnalyzer.java:101)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1767)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2139)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2106)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1973)
	at picocli.CommandLine.execute(CommandLine.java:1902)
	at com.ibm.cldk.CodeAnalyzer.main(CodeAnalyzer.java:92)
Caused by: java.lang.IllegalStateException: Could not file a valid gradle command. I did not find gradlew or gradle in the project directory or in the system PATH.
	at com.ibm.cldk.utils.BuildProject.getGradleCmd(BuildProject.java:61)
	at com.ibm.cldk.utils.BuildProject.<clinit>(BuildProject.java:24)
	... 9 more
```

This is 100% reproducible.
